insert into public.communes (wilaya_code, name_fr, name_ar) values
('01','Adrar',null),
('01','Tamest',null),
('01','Reggane',null),
('01','In Zghmir',null),
('01','Tit',null),
('01','Tsabit',null),
('01','Zaouiet Kounta',null),
('01','Aoulef',null),
('01','Tamekten',null),
('01','Tamantit',null),
('01','Fenoughil',null),
('01','Sali',null),
('01','Akabli',null),
('01','Ouled Ahmed Tammi',null),
('01','Bouda',null),
('01','Sebaa',null),
('02','Abou El Hassan',null),
('02','AÃ¯n Merane',null),
('02','BÃ©nairia',null),
('02','Beni Bouateb',null),
('02','Beni Haoua',null),
('02','Beni Rached',null),
('02','Boukadir',null),
('02','Bouzeghaia',null),
('02','Breira',null),
('02','Chettia',null),
('02','Chlef',null),
('02','Dahra',null),
('02','El Hadjadj',null),
('02','El Karimia',null),
('02','El Marsa',null),
('02','Harchoun',null),
('02','Harenfa',null),
('02','Labiod Medjadja',null),
('02','Moussadek',null),
('02','Oued Fodda',null),
('02','Oued Goussine',null),
('02','Oued Sly',null),
('02','Ouled Abbes',null),
('02','Ouled Ben Abdelkader',null),
('02','Ouled Fares',null),
('02','Oum Drou',null),
('02','Sendjas',null),
('02','Sidi Abderrahmane',null),
('02','Sidi Akkacha',null),
('02','Sobha',null),
('02','Tadjena',null),
('02','Talassa',null),
('02','Taougrite',null),
('02','TÃ©nÃ¨s',null),
('02','Zeboudja',null),
('03','Laghouat',null),
('03','Ksar El Hirane',null),
('03','Bennasser Benchohra',null),
('03','Sidi Makhlouf',null),
('03','Hassi Delaa',null),
('03','Hassi R''Mel',null),
('03','AÃ¯n Madhi',null),
('03','Tadjemout',null),
('03','Kheneg',null),
('03','Gueltat Sidi Saad',null),
('03','AÃ¯n Sidi Ali',null),
('03','Beidha',null),
('03','Brida',null),
('03','El Ghicha',null),
('03','Hadj Mechri',null),
('03','Sebgag',null),
('03','Taouiala',null),
('03','Tadjrouna',null),
('03','Aflou',null),
('03','El Assafia',null),
('03','Oued Morra',null),
('03','Oued M''Zi',null),
('03','El Houaita',null),
('03','Sidi Bouzid',null),
('04','Oum el Bouaghi',null),
('04','AÃ¯n BeÃ¯da',null),
('04','AÃ¯n M''lila',null),
('04','Behir Chergui',null),
('04','El Amiria',null),
('04','Sigus',null),
('04','El Belala',null),
('04','AÃ¯n Babouche',null),
('04','Berriche',null),
('04','Ouled Hamla',null),
('04','Dhalaa',null),
('04','AÃ¯n Kercha',null),
('04','Hanchir Toumghani',null),
('04','El Djazia',null),
('04','AÃ¯n Diss',null),
('04','Fkirina',null),
('04','Souk Naamane',null),
('04','Zorg',null),
('04','El Fedjoudj Boughrara Saoudi',null),
('04','Ouled ZouaÃ¯',null),
('04','Bir Chouhada',null),
('04','Ksar Sbahi',null),
('04','Oued Nini',null),
('04','Meskiana',null),
('04','AÃ¯n Fakroun',null),
('04','Rahia',null),
('04','AÃ¯n Zitoun',null),
('04','Ouled Gacem',null),
('04','El Harmilia',null),
('05','Batna',null),
('05','Ghassira',null),
('05','Maafa',null),
('05','Merouana',null),
('05','Seriana',null),
('05','Menaa',null),
('05','El Madher',null),
('05','Tazoult',null),
('05','N''Gaous',null),
('05','Guigba',null),
('05','Inoughissen',null),
('05','Ouyoun El Assafir',null),
('05','Djerma',null),
('05','Bitam',null),
('05','Abdelkader Azil',null),
('05','Arris',null),
('05','Kimmel',null),
('05','Tilatou',null),
('05','AÃ¯n Djasser',null),
('05','Ouled Sellam',null),
('05','Tigherghar',null),
('05','AÃ¯n Yagout',null),
('05','Fesdis',null),
('05','Sefiane',null),
('05','Rahbat',null),
('05','Tighanimine',null),
('05','Lemsane',null),
('05','Ksar Bellezma',null),
('05','Seggana',null),
('05','Ichmoul',null),
('05','Foum Toub',null),
('05','Ben Foudhala El Hakania',null),
('05','Oued El Ma',null),
('05','Talkhamt',null),
('05','Bouzina',null),
('05','Chemora',null),
('05','Oued Chaaba',null),
('05','Taxlent',null),
('05','Gosbat',null),
('05','Ouled Aouf',null),
('05','Boumagueur',null),
('05','Barika',null),
('05','Djezar',null),
('05','T''Kout',null),
('05','AÃ¯n Touta',null),
('05','Hidoussa',null),
('05','Teniet El Abed',null),
('05','Oued Taga',null),
('05','Ouled Fadel',null),
('05','Timgad',null),
('05','Ras El Aioun',null),
('05','Chir',null),
('05','Ouled Si Slimane',null),
('05','Zanat El Beida',null),
('05','M''doukel',null),
('05','Ouled Ammar',null),
('05','El Hassi',null),
('05','Lazrou',null),
('05','Boumia (Batna)',null),
('05','Boulhilat',null),
('05','LarbaÃ¢',null),
('06','BÃ©jaÃ¯a',null),
('06','Amizour',null),
('06','Ferraoun',null),
('06','Taourirt Ighil',null),
('06','Chellata',null),
('06','Tamokra',null),
('06','Timezrit',null),
('06','Souk El TÃ©nine',null),
('06','M''cisna',null),
('06','Tinabdher',null),
('06','Tichy',null),
('06','Semaoun',null),
('06','Kendira',null),
('06','Tifra',null),
('06','Ighram',null),
('06','Amalou',null),
('06','Ighil Ali',null),
('06','FenaÃ¯a Ilmaten',null),
('06','Toudja',null),
('06','Darguina',null),
('06','Sidi Ayad',null),
('06','Aokas',null),
('06','Ait Djellil',null),
('06','Adekar',null),
('06','Akbou',null),
('06','Seddouk',null),
('06','Tazmalt',null),
('06','AÃ¯t R''zine',null),
('06','Chemini',null),
('06','Souk Oufella',null),
('06','Tibane',null),
('06','Tala Hamza',null),
('06','Barbacha',null),
('06','AÃ¯t Ksila',null),
('06','Ouzellaguen',null),
('06','Bouhamza',null),
('06','Taskriout',null),
('06','AÃ¯t Mellikeche',null),
('06','Sidi AÃ¯ch',null),
('06','El Kseur',null),
('06','Melbou',null),
('06','Akfadou',null),
('06','Leflaye',null),
('06','Kherrata',null),
('06','DraÃ¢ El KaÃ¯d',null),
('06','Tamridjet',null),
('06','AÃ¯t Smail',null),
('06','Boukhelifa',null),
('06','Tizi N''Berber',null),
('06','AÃ¯t Maouche',null),
('06','Oued Ghir',null),
('06','Boudjellil',null),
('07','AÃ¯n Naga',null),
('07','AÃ¯n Zaatout',null),
('07','Biskra',null),
('07','Bordj Ben Azzouz',null),
('07','Bouchagroune',null),
('07','Branis',null),
('07','Chetma',null),
('07','Djemorah',null),
('07','El Feidh',null),
('07','El Ghrous',null),
('07','El Hadjeb',null),
('07','El Haouch',null),
('07','El Kantara',null),
('07','El Mizaraa',null),
('07','El Outaya',null),
('07','Foughala',null),
('07','Khenguet Sidi Nadji',null),
('07','Lichana',null),
('07','Lioua',null),
('07','M''Chouneche',null),
('07','Mekhadma',null),
('07','M''Lili',null),
('07','Oumache',null),
('07','Ourlal',null),
('07','Sidi Okba',null),
('07','Tolga',null),
('07','Zeribet El Oued',null),
('08','BÃ©char',null),
('08','Erg Ferradj',null),
('08','Meridja',null),
('08','Lahmar',null),
('08','Mechraa Houari Boumedienne',null),
('08','Kenadsa',null),
('08','Taghit',null),
('08','Boukais',null),
('08','Mougheul',null),
('08','Abadla',null),
('08','Beni Ounif',null),
('09','Blida',null),
('09','Chebli',null),
('09','Bouinan',null),
('09','Oued Alleug',null),
('09','Ouled YaÃ¯ch',null),
('09','ChrÃ©a',null),
('09','El Affroun',null),
('09','Chiffa',null),
('09','Hammam Melouane',null),
('09','Benkhelil',null),
('09','Soumaa',null),
('09','Mouzaia',null),
('09','Souhane',null),
('09','Meftah',null),
('09','Ouled Slama',null),
('09','Boufarik',null),
('09','Larbaa',null),
('09','Oued Djer',null),
('09','Beni Tamou',null),
('09','Bouarfa',null),
('09','Beni Mered',null),
('09','Bougara',null),
('09','Guerouaou',null),
('09','AÃ¯n Romana',null),
('09','Djebabra',null),
('10','AÃ¯n Bessem',null),
('10','Hanif',null),
('10','Aghbalou',null),
('10','AÃ¯n El Hadjar',null),
('10','Ahl El Ksar',null),
('10','AÃ¯n Laloui',null),
('10','Ath Mansour',null),
('10','Aomar',null),
('10','AÃ¯n El Turc',null),
('10','AÃ¯t Laziz',null),
('10','Bouderbala',null),
('10','Bechloul',null),
('10','Bir Ghbalou',null),
('10','Boukram',null),
('10','Bordj Okhriss',null),
('10','Bouira',null),
('10','Chorfa',null),
('10','Dechmia',null),
('10','Dirrah',null),
('10','Djebahia',null),
('10','El Hakimia',null),
('10','El Hachimia',null),
('10','El Adjiba',null),
('10','El Khabouzia',null),
('10','El Mokrani',null),
('10','El Asnam',null),
('10','Guerrouma',null),
('10','Haizer',null),
('10','Hadjera Zerga',null),
('10','Kadiria',null),
('10','Lakhdaria',null),
('10','M''Chedallah',null),
('10','Mezdour',null),
('10','Maala',null),
('10','Maamora',null),
('10','Oued El Berdi',null),
('10','Ouled Rached',null),
('10','Raouraoua',null),
('10','Ridane',null),
('10','Saharidj',null),
('10','Sour El Ghouzlane',null),
('10','Souk El Khemis',null),
('10','Taguedit',null),
('10','Taghzout',null),
('10','Zbarbar',null),
('11','Tamanrasset',null),
('11','Abalessa',null),
('11','Idles',null),
('11','Tazrouk',null),
('11','In Amguel',null),
('12','TÃ©bessa',null),
('12','Bir el Ater',null),
('12','Cheria',null),
('12','Stah Guentis',null),
('12','El Aouinet',null),
('12','El Houidjbet',null),
('12','Safsaf El Ouesra',null),
('12','Hammamet',null),
('12','Negrine',null),
('12','Bir Mokkadem',null),
('12','El Kouif',null),
('12','Morsott',null),
('12','El Ogla',null),
('12','Bir Dheb',null),
('12','Ogla Melha',null),
('12','Guorriguer',null),
('12','Bekkaria',null),
('12','Boukhadra',null),
('12','Ouenza',null),
('12','El Ma Labiodh',null),
('12','Oum Ali',null),
('12','Tlidjene',null),
('12','AÃ¯n Zerga',null),
('12','El Meridj',null),
('12','Boulhaf Dir',null),
('12','Bedjene',null),
('12','El Mezeraa',null),
('12','Ferkane',null),
('13','Tlemcen',null),
('13','Beni Mester',null),
('13','AÃ¯n Tallout',null),
('13','Remchi',null),
('13','El Fehoul',null),
('13','Sabra',null),
('13','Ghazaouet',null),
('13','Souani',null),
('13','Djebala',null),
('13','El Gor',null),
('13','Oued Lakhdar',null),
('13','AÃ¯n Fezza',null),
('13','Ouled Mimoun',null),
('13','Amieur',null),
('13','AÃ¯n Youcef',null),
('13','Zenata',null),
('13','Beni Snous',null),
('13','Bab El Assa',null),
('13','Dar Yaghmouracene',null),
('13','Fellaoucene',null),
('13','Azails',null),
('13','Sebaa Chioukh',null),
('13','Terny Beni Hdiel',null),
('13','Bensekrane',null),
('13','AÃ¯n Nehala',null),
('13','Hennaya',null),
('13','Maghnia',null),
('13','Hammam Boughrara',null),
('13','Souahlia',null),
('13','MSirda Fouaga',null),
('13','AÃ¯n Fetah',null),
('13','El Aricha',null),
('13','Souk Tlata',null),
('13','Sidi Abdelli',null),
('13','Sebdou',null),
('13','Beni Ouarsous',null),
('13','Sidi Medjahed',null),
('13','Beni Boussaid',null),
('13','Marsa Ben M''Hidi',null),
('13','Nedroma',null),
('13','Sidi Djillali',null),
('13','Beni Bahdel',null),
('13','El Bouihi',null),
('13','HonaÃ¯ne',null),
('13','Tienet',null),
('13','Ouled Riyah',null),
('13','Bouhlou',null),
('13','Beni Khellad',null),
('13','AÃ¯n Ghoraba',null),
('13','Chetouane',null),
('13','Mansourah',null),
('13','Beni Semiel',null),
('13','AÃ¯n Kebira',null),
('14','AÃ¯n Bouchekif',null),
('14','AÃ¯n Deheb',null),
('14','AÃ¯n El Hadid',null),
('14','AÃ¯n Kermes',null),
('14','AÃ¯n Dzarit',null),
('14','Bougara',null),
('14','Chehaima',null),
('14','Dahmouni',null),
('14','Djebilet Rosfa',null),
('14','Djillali Ben Amar',null),
('14','Faidja',null),
('14','Frenda',null),
('14','Guertoufa',null),
('14','Hamadia',null),
('14','Ksar Chellala',null),
('14','Madna',null),
('14','Mahdia',null),
('14','Mechraa Safa',null),
('14','Medrissa',null),
('14','Medroussa',null),
('14','Meghila',null),
('14','Mellakou',null),
('14','Nadorah',null),
('14','Naima',null),
('14','Oued Lilli',null),
('14','Rahouia',null),
('14','Rechaiga',null),
('14','Sebaine',null),
('14','Sebt',null),
('14','Serghine',null),
('14','Si Abdelghani',null),
('14','Sidi Abderahmane',null),
('14','Sidi Ali Mellal',null),
('14','Sidi Bakhti',null),
('14','Sidi Hosni',null),
('14','Sougueur',null),
('14','Tagdemt',null),
('14','Takhemaret',null),
('14','Tiaret',null),
('14','Tidda',null),
('14','Tousnina',null),
('14','Zmalet El Emir Abdelkader',null),
('15','Tizi Ouzou',null),
('15','Ain El Hammam',null),
('15','Akbil',null),
('15','Freha',null),
('15','SouamaÃ¢',null),
('15','Mechtras',null),
('15','Irdjen',null),
('15','Timizart',null),
('15','Makouda',null),
('15','DraÃ¢ El Mizan',null),
('15','Tizi Gheniff',null),
('15','Bounouh',null),
('15','AÃ¯t ChafÃ¢a',null),
('15','Frikat',null),
('15','Beni AÃ¯ssi',null),
('15','Beni Zmenzer',null),
('15','IferhounÃ¨ne',null),
('15','Azazga',null),
('15','Illoula Oumalou',null),
('15','Yakouren',null),
('15','LarbaÃ¢ Nath Irathen',null),
('15','Tizi Rached',null),
('15','Zekri',null),
('15','Ouaguenoun',null),
('15','AÃ¯n Zaouia',null),
('15','M''Kira',null),
('15','AÃ¯t Yahia',null),
('15','AÃ¯t Mahmoud',null),
('15','MÃ¢atkas',null),
('15','AÃ¯t Boumahdi',null),
('15','Abi Youcef',null),
('15','Beni Douala',null),
('15','Illilten',null),
('15','Bouzguen',null),
('15','AÃ¯t Aggouacha',null),
('15','Ouadhia',null),
('15','Azeffoun',null),
('15','Tigzirt',null),
('15','AÃ¯t AÃ¯ssa Mimoun',null),
('15','Boghni',null),
('15','Ifigha',null),
('15','AÃ¯t Oumalou',null),
('15','Tirmitine',null),
('15','Akerrou',null),
('15','Yatafen',null),
('15','Ath Zikki',null),
('15','DraÃ¢ Ben Khedda',null)
on conflict (wilaya_code, name_fr) do update set
  name_ar = excluded.name_ar;

insert into public.communes (wilaya_code, name_fr, name_ar) values
('15','Ouacif',null),
('15','Idjeur',null),
('15','Mekla',null),
('15','Tizi N''Tleta',null),
('15','AÃ¯t Yenni',null),
('15','Aghribs',null),
('15','Iflissen',null),
('15','Boudjima',null),
('15','AÃ¯t Yahia Moussa',null),
('15','Souk El Thenine',null),
('15','AÃ¯t Khellili',null),
('15','Sidi Namane',null),
('15','Iboudraren',null),
('15','Agouni Gueghrane',null),
('15','Mizrana',null),
('15','Imsouhel',null),
('15','TadmaÃ¯t',null),
('15','AÃ¯t Bouadou',null),
('15','Assi Youcef',null),
('15','AÃ¯t Toudert',null),
('16','Alger Centre',null),
('16','Sidi M''Hamed',null),
('16','El Madania',null),
('16','Belouizdad',null),
('16','Bab El Oued',null),
('16','Bologhine',null),
('16','Casbah',null),
('16','Oued Koriche',null),
('16','Bir Mourad RaÃ¯s',null),
('16','El Biar',null),
('16','Bouzareah',null),
('16','Birkhadem',null),
('16','El Harrach',null),
('16','Baraki',null),
('16','Oued Smar',null),
('16','Bachdjerrah',null),
('16','Hussein Dey',null),
('16','Kouba',null),
('16','Bourouba',null),
('16','Dar El BeÃ¯da',null),
('16','Bab Ezzouar',null),
('16','Ben Aknoun',null),
('16','Dely Ibrahim',null),
('16','El Hammamet',null),
('16','RaÃ¯s Hamidou',null),
('16','Djasr Kasentina',null),
('16','El Mouradia',null),
('16','Hydra',null),
('16','Mohammadia',null),
('16','Bordj El Kiffan',null),
('16','El Magharia',null),
('16','Beni Messous',null),
('16','Les Eucalyptus',null),
('16','Birtouta',null),
('16','Tessala El Merdja',null),
('16','Ouled Chebel',null),
('16','Sidi Moussa',null),
('16','AÃ¯n Taya',null),
('16','Bordj El Bahri',null),
('16','El Marsa',null),
('16','H''raoua',null),
('16','RouÃ¯ba',null),
('16','ReghaÃ¯a',null),
('16','AÃ¯n Benian',null),
('16','Staoueli',null),
('16','Zeralda',null),
('16','Mahelma',null),
('16','Rahmania',null),
('16','Souidania',null),
('16','Cheraga',null),
('16','Ouled Fayet',null),
('16','El Achour',null),
('16','Draria',null),
('16','Douera',null),
('16','Baba Hassen',null),
('16','Khraicia',null),
('16','Saoula',null),
('17','AÃ¯n Chouhada',null),
('17','AÃ¯n El Ibel',null),
('17','AÃ¯n Feka',null),
('17','AÃ¯n Maabed',null),
('17','AÃ¯n Oussara',null),
('17','Amourah',null),
('17','Benhar',null),
('17','Beni Yagoub',null),
('17','Birine',null),
('17','Bouira Lahdab',null),
('17','Charef',null),
('17','Dar Chioukh',null),
('17','Deldoul',null),
('17','Djelfa',null),
('17','Douis',null),
('17','El Guedid',null),
('17','El Idrissia',null),
('17','El Khemis',null),
('17','Faidh El Botma',null),
('17','Guernini',null),
('17','Guettara',null),
('17','Had Sahary',null),
('17','Hassi Bahbah',null),
('17','Hassi El Euch',null),
('17','Hassi Fedoul',null),
('17','Messaad',null),
('17','M''Liliha',null),
('17','Moudjebara',null),
('17','Oum Laadham',null),
('17','Sed Rahal',null),
('17','Selmana',null),
('17','Sidi Baizid',null),
('17','Sidi Ladjel',null),
('17','Tadmit',null),
('17','Zaafrane',null),
('17','Zaccar',null),
('18','Jijel',null),
('18','Eraguene',null),
('18','El Aouana',null),
('18','Ziama Mansouriah',null),
('18','Taher',null),
('18','Emir Abdelkader',null),
('18','Chekfa',null),
('18','Chahna',null),
('18','El Milia',null),
('18','Sidi Maarouf',null),
('18','Settara',null),
('18','El Ancer',null),
('18','Sidi Abdelaziz',null),
('18','Kaous',null),
('18','Ghebala',null),
('18','Bouraoui Belhadef',null),
('18','Djimla',null),
('18','Selma Benziada',null),
('18','Boucif Ouled Askeur',null),
('18','El Kennar Nouchfi',null),
('18','Ouled Yahia Khedrouche',null),
('18','Boudriaa Ben Yadjis',null),
('18','KheÃ¯ri Oued Adjoul',null),
('18','Texenna',null),
('18','Djemaa Beni Habibi',null),
('18','Bordj Tahar',null),
('18','Ouled Rabah',null),
('18','Ouadjana',null),
('19','AÃ¯n Abessa',null),
('19','AÃ¯n Arnat',null),
('19','AÃ¯n Azel',null),
('19','AÃ¯n El Kebira',null),
('19','AÃ¯n Lahdjar',null),
('19','AÃ¯n Legradj',null),
('19','AÃ¯n Oulmene',null),
('19','AÃ¯n Roua',null),
('19','AÃ¯n Sebt',null),
('19','AÃ¯t Naoual Mezada',null),
('19','AÃ¯t Tizi',null),
('19','AÃ¯t Wertilan',null),
('19','Amoucha',null),
('19','Babor',null),
('19','Bazer Sakhra',null),
('19','Beidha Bordj',null),
('19','Belaa',null),
('19','Beni Aziz',null),
('19','Beni Chebana',null),
('19','Beni Fouda',null),
('19','Beni Hocine',null),
('19','Beni Mouhli',null),
('19','Bir El Arch',null),
('19','Bir Haddada',null),
('19','Bouandas',null),
('19','Bougaa',null),
('19','Bousselam',null),
('19','Boutaleb',null),
('19','Dehamcha',null),
('19','Djemila',null),
('19','Draa Kebila',null),
('19','El Eulma',null),
('19','El Ouldja',null),
('19','El Ouricia',null),
('19','Guellal',null),
('19','Guelta Zerka',null),
('19','Guenzet',null),
('19','Guidjel',null),
('19','Hamma',null),
('19','Hammam Guergour',null),
('19','Hammam Soukhna',null),
('19','Harbil',null),
('19','Ksar El Abtal',null),
('19','Maaouia',null),
('19','Maoklane',null),
('19','Mezloug',null),
('19','Oued El Barad',null),
('19','Ouled Addouane',null),
('19','Ouled Sabor',null),
('19','Ouled Si Ahmed',null),
('19','Ouled Tebben',null),
('19','Rasfa',null),
('19','Salah Bey',null),
('19','Serdj El Ghoul',null),
('19','SÃ©tif',null),
('19','Tachouda',null),
('19','Talaifacene',null),
('19','Taya',null),
('19','Tella',null),
('19','Tizi N''Bechar',null),
('20','AÃ¯n El Hadjar',null),
('20','AÃ¯n Sekhouna',null),
('20','AÃ¯n Soltane',null),
('20','Doui Thabet',null),
('20','El Hassasna',null),
('20','Hounet',null),
('20','Maamora',null),
('20','Moulay Larbi',null),
('20','Ouled Brahim',null),
('20','Ouled Khaled',null),
('20','SaÃ¯da',null),
('20','Sidi Ahmed',null),
('20','Sidi Amar',null),
('20','Sidi Boubekeur',null),
('20','Tircine',null),
('20','Youb',null),
('21','AÃ¯n Bouziane',null),
('21','AÃ¯n Charchar',null),
('21','AÃ¯n Kechra',null),
('21','AÃ¯n Zouit',null),
('21','Azzaba',null),
('21','Bekkouche Lakhdar',null),
('21','Bin El Ouiden',null),
('21','Ben Azzouz',null),
('21','Beni Bechir',null),
('21','Beni Oulbane',null),
('21','Beni Zid',null),
('21','Bouchtata',null),
('21','Cheraia',null),
('21','Collo',null),
('21','Djendel Saadi Mohamed',null),
('21','El Ghedir',null),
('21','El Hadaiek',null),
('21','El Harrouch',null),
('21','El Marsa',null),
('21','Emdjez Edchich',null),
('21','Es Sebt',null),
('21','Filfila',null),
('21','Hamadi Krouma',null),
('21','Kanoua',null),
('21','Kerkera',null),
('21','Kheneg Mayoum',null),
('21','Oued Zehour',null),
('21','Ouldja Boulballout',null),
('21','Ouled Attia',null),
('21','Ouled Hbaba',null),
('21','Oum Toub',null),
('21','Ramdane Djamel',null),
('21','Salah Bouchaour',null),
('21','Sidi Mezghiche',null),
('21','Skikda',null),
('21','Tamalous',null),
('21','Zerdaza',null),
('21','Zitouna',null),
('22','AÃ¯n Adden',null),
('22','AÃ¯n El Berd',null),
('22','AÃ¯n Kada',null),
('22','AÃ¯n Thrid',null),
('22','AÃ¯n Tindamine',null),
('22','Amarnas',null),
('22','Badredine El Mokrani',null),
('22','Belarbi',null),
('22','Ben Badis',null),
('22','Benachiba Chelia',null),
('22','Bir El Hammam',null),
('22','Boudjebaa El Bordj',null),
('22','Boukhanafis',null),
('22','Chettouane Belaila',null),
('22','Dhaya',null),
('22','El HaÃ§aiba',null),
('22','Hassi Dahou',null),
('22','Hassi Zehana',null),
('22','Lamtar',null),
('22','Makedra',null),
('22','Marhoum',null),
('22','M''Cid',null),
('22','Merine',null),
('22','Mezaourou',null),
('22','Mostefa Ben Brahim',null),
('22','Moulay Slissen',null),
('22','Oued Sebaa',null),
('22','Oued Sefioun',null),
('22','Oued Taourira',null),
('22','Ras El Ma',null),
('22','Redjem Demouche',null),
('22','Sehala Thaoura',null),
('22','Sfisef',null),
('22','Sidi Ali Benyoub',null),
('22','Sidi Ali Boussidi',null),
('22','Sidi Bel Abbes',null),
('22','Sidi Brahim',null),
('22','Sidi Chaib',null),
('22','Sidi Daho des Zairs',null),
('22','Sidi Hamadouche',null),
('22','Sidi Khaled',null),
('22','Sidi Lahcene',null),
('22','Sidi Yacoub',null),
('22','Tabia',null),
('22','Tafissour',null),
('22','Taoudmout',null),
('22','Teghalimet',null),
('22','Telagh',null),
('22','Tenira',null),
('22','Tessala',null),
('22','Tilmouni',null),
('22','Zerouala',null),
('23','Annaba',null),
('23','Berrahal',null),
('23','El Hadjar',null),
('23','Eulma',null),
('23','El Bouni',null),
('23','Oued El Aneb',null),
('23','Cheurfa',null),
('23','SeraÃ¯di',null),
('23','AÃ¯n Berda',null),
('23','ChetaÃ¯bi',null),
('23','Sidi Amar',null),
('23','Treat',null),
('24','AÃ¯n Ben Beida',null),
('24','AÃ¯n Larbi',null),
('24','AÃ¯n Makhlouf',null),
('24','AÃ¯n Reggada',null),
('24','AÃ¯n Sandel',null),
('24','Belkheir',null),
('24','Ben Djerrah',null),
('24','Beni Mezline',null),
('24','Bordj Sabath',null),
('24','Bouhachana',null),
('24','Bouhamdane',null),
('24','Bouati Mahmoud',null),
('24','Bouchegouf',null),
('24','Boumahra Ahmed',null),
('24','Dahouara',null),
('24','Djeballah Khemissi',null),
('24','El Fedjoudj',null),
('24','Guellat Bou Sbaa',null),
('24','Guelma',null),
('24','Hammam Debagh',null),
('24','Hammam N''Bail',null),
('24','HÃ©liopolis',null),
('24','Houari BoumÃ©diÃ¨ne',null),
('24','Khezarra',null),
('24','Medjez Amar',null),
('24','Medjez Sfa',null),
('24','Nechmaya',null),
('24','Oued Cheham',null),
('24','Oued Fragha',null),
('24','Oued Zenati',null),
('24','Ras El Agba',null),
('24','Roknia',null),
('24','Sellaoua Announa',null),
('24','Tamlouka',null),
('25','AÃ¯n Abid',null),
('25','AÃ¯n Smara',null),
('25','Beni Hamiden',null),
('25','Constantine',null),
('25','Didouche Mourad',null),
('25','El Khroub',null),
('25','Hamma Bouziane',null),
('25','Ibn Badis',null),
('25','Ibn Ziad',null),
('25','Messaoud Boudjriou',null),
('25','Ouled Rahmoune',null),
('25','Zighoud Youcef',null),
('26','AÃ¯n Boucif',null),
('26','AÃ¯n Ouksir',null),
('26','Aissaouia',null),
('26','Aziz',null),
('26','Baata',null),
('26','Benchicao',null),
('26','Beni Slimane',null),
('26','Berrouaghia',null),
('26','Bir Ben Laabed',null),
('26','Boghar',null),
('26','Bou Aiche',null),
('26','Bouaichoune',null),
('26','Bouchrahil',null),
('26','Boughezoul',null),
('26','Bouskene',null),
('26','Chahbounia',null),
('26','Chellalet El Adhaoura',null),
('26','Cheniguel',null),
('26','Derrag',null),
('26','Deux Bassins',null),
('26','Djouab',null),
('26','Draa Essamar',null),
('26','El Azizia',null),
('26','El Guelb El Kebir',null),
('26','El Hamdania',null),
('26','El Omaria',null),
('26','El Ouinet',null),
('26','Hannacha',null),
('26','Kef Lakhdar',null),
('26','Khams Djouamaa',null),
('26','Ksar Boukhari',null),
('26','Meghraoua',null),
('26','MÃ©dÃ©a',null),
('26','Moudjbar',null),
('26','Meftaha',null),
('26','Mezerana',null),
('26','Mihoub',null),
('26','Ouamri',null),
('26','Oued Harbil',null),
('26','Ouled Antar',null),
('26','Ouled Bouachra',null),
('26','Ouled Brahim',null),
('26','Ouled Deide',null),
('26','Ouled Hellal',null),
('26','Ouled Maaref',null),
('26','Oum El Djalil',null),
('26','Ouzera',null),
('26','Rebaia',null),
('26','Saneg',null),
('26','Sedraia',null),
('26','Seghouane',null),
('26','Si Mahdjoub',null),
('26','Sidi Damed',null),
('26','Sidi Errabia',null),
('26','Sidi Naamanez',null),
('26','Sidi Zahar',null),
('26','Sidi Ziane',null),
('26','Souagui',null),
('26','Tablat',null),
('26','Tafraout',null),
('26','Tamesguida',null),
('26','Tizi Mahdi',null),
('26','Tlatet Eddouar',null),
('26','Zoubiria',null),
('27','Abdelmalek Ramdane',null),
('27','Achaacha',null),
('27','AÃ¯n Boudinar',null),
('27','AÃ¯n Nouissy',null),
('27','AÃ¯n Sidi Cherif',null),
('27','AÃ¯n Tedles',null),
('27','Blad Touahria',null),
('27','Bouguirat',null),
('27','El Hassaine',null),
('27','Fornaka',null),
('27','Hadjadj',null),
('27','Hassi Mameche',null),
('27','Khadra',null),
('27','Kheireddine',null),
('27','Mansourah',null),
('27','Mesra',null),
('27','Mazagran',null),
('27','Mostaganem',null),
('27','Nekmaria',null),
('27','Oued El Kheir',null),
('27','Ouled Boughalem',null),
('27','Ouled Maallah',null),
('27','Safsaf',null),
('27','Sayada',null),
('27','Sidi Ali',null),
('27','Sidi Belattar',null),
('27','Sidi Lakhdar',null),
('27','Sirat',null),
('27','Souaflia',null),
('27','Sour',null),
('27','Stidia',null),
('27','Tazgait',null),
('28','AÃ¯n El Hadjel',null),
('28','AÃ¯n El Melh',null),
('28','AÃ¯n Errich',null),
('28','AÃ¯n Fares',null),
('28','AÃ¯n Khadra',null),
('28','Belaiba',null),
('28','Ben Srour',null),
('28','Beni Ilmane',null),
('28','Benzouh',null),
('28','Berhoum',null),
('28','Bir Foda',null),
('28','Bou SaÃ¢da',null),
('28','Bouti Sayah',null),
('28','Chellal',null),
('28','Dehahna',null),
('28','Djebel Messaad',null),
('28','El Hamel',null),
('28','El Houamed',null),
('28','Hammam Dhalaa',null),
('28','Khettouti Sed El Djir',null),
('28','Khoubana',null),
('28','Maadid',null),
('28','Maarif',null),
('28','Magra',null),
('28','M''Cif',null),
('28','Medjedel',null),
('28','Mohammed Boudiaf',null),
('28','M''Sila',null),
('28','M''Tarfa',null),
('28','Ouanougha',null),
('28','Ouled Addi Guebala',null),
('28','Ouled Atia',null),
('28','Ouled Derradj',null),
('28','Ouled Madhi',null),
('28','Ouled Mansour',null),
('28','Ouled Sidi Brahim',null),
('28','Ouled Slimane',null),
('28','Oultem',null),
('28','Sidi AÃ¯ssa',null)
on conflict (wilaya_code, name_fr) do update set
  name_ar = excluded.name_ar;

insert into public.communes (wilaya_code, name_fr, name_ar) values
('28','Sidi Ameur',null),
('28','Sidi Hadjeres',null),
('28','Sidi M''Hamed',null),
('28','Slim',null),
('28','Souamaa',null),
('28','Tamsa',null),
('28','Tarmount',null),
('28','Zarzour',null),
('29','AÃ¯n Fares',null),
('29','AÃ¯n Fekan',null),
('29','AÃ¯n Ferah',null),
('29','AÃ¯n Fras',null),
('29','AlaÃ¯mia',null),
('29','Aouf',null),
('29','Beniane',null),
('29','Bou Hanifia',null),
('29','Bou Henni',null),
('29','Chorfa',null),
('29','El Bordj',null),
('29','El Gaada',null),
('29','El Ghomri',null),
('29','El Guettana',null),
('29','El Keurt',null),
('29','El Menaouer',null),
('29','Ferraguig',null),
('29','Froha',null),
('29','Gharrous',null),
('29','Guerdjoum',null),
('29','Ghriss',null),
('29','Hachem',null),
('29','Hacine',null),
('29','Khalouia',null),
('29','Makdha',null),
('29','Mamounia',null),
('29','Maoussa',null),
('29','Mascara',null),
('29','Matemore',null),
('29','Mocta Douz',null),
('29','Mohammadia',null),
('29','Nesmoth',null),
('29','Oggaz',null),
('29','Oued El Abtal',null),
('29','Oued Taria',null),
('29','Ras El AÃ¯n Amirouche',null),
('29','Sedjerara',null),
('29','Sehailia',null),
('29','Sidi Abdeldjebar',null),
('29','Sidi Abdelmoumen',null),
('29','Sidi Kada',null),
('29','Sidi Boussaid',null),
('29','Sig',null),
('29','Tighennif',null),
('29','Tizi',null),
('29','Zahana',null),
('29','Zelmata',null),
('30','AÃ¯n Beida',null),
('30','Hassi Ben Abdellah',null),
('30','Hassi Messaoud',null),
('30','N''Goussa',null),
('30','Ouargla',null),
('30','Rouissat',null),
('30','Sidi Khouiled',null),
('31','Oran',null),
('31','Gdyel',null),
('31','Bir El Djir',null),
('31','Hassi Bounif',null),
('31','Es Senia',null),
('31','Arzew',null),
('31','Bethioua',null),
('31','Marsat El Hadjadj',null),
('31','AÃ¯n El Turk',null),
('31','El AnÃ§or',null),
('31','Oued Tlelat',null),
('31','Tafraoui',null),
('31','Sidi Chami',null),
('31','Boufatis',null),
('31','Mers El KÃ©bir',null),
('31','Bou Sfer',null),
('31','El Kerma',null),
('31','El Braya',null),
('31','Hassi Ben Okba',null),
('31','Ben Freha',null),
('31','Hassi Mefsoukh',null),
('31','Sidi Benyebka',null),
('31','Misserghin',null),
('31','Boutlelis',null),
('31','AÃ¯n El Kerma',null),
('31','AÃ¯n El Bia',null),
('32','El Bayadh',null),
('32','Rogassa',null),
('32','Stitten',null),
('32','Brezina',null),
('32','Ghassoul',null),
('32','Boualem',null),
('32','El Abiodh Sidi Cheikh',null),
('32','AÃ¯n El Orak',null),
('32','Arbaouat',null),
('32','Bougtoub',null),
('32','El Kheiter',null),
('32','Kef El Ahmar',null),
('32','Boussemghoun',null),
('32','Chellala',null),
('32','Kraakda',null),
('32','El Bnoud',null),
('32','Cheguig',null),
('32','Sidi Ameur',null),
('32','El Mehara',null),
('32','Tousmouline',null),
('32','Sidi Slimane',null),
('32','Sidi Tifour',null),
('33','Illizi',null),
('33','Debdeb',null),
('33','Bordj Omar Driss',null),
('33','In Amenas',null),
('34','AÃ¯n Taghrout',null),
('34','AÃ¯n Tesra',null),
('34','Belimour',null),
('34','Ben Daoud',null),
('34','Bir Kasdali',null),
('34','Bordj Bou Arreridj',null),
('34','Bordj GhÃ©dir',null),
('34','Bordj Zemoura',null),
('34','Colla',null),
('34','Djaafra',null),
('34','El Ach',null),
('34','El Achir',null),
('34','El Anseur',null),
('34','El Hamadia',null),
('34','El Main',null),
('34','El M''hir',null),
('34','Ghilassa',null),
('34','Haraza',null),
('34','Hasnaoua',null),
('34','Khelil',null),
('34','Ksour',null),
('34','Mansoura',null),
('34','Medjana',null),
('34','Ouled Brahem',null),
('34','Ouled Dahmane',null),
('34','Ouled Sidi Brahim',null),
('34','Rabta',null),
('34','Ras El Oued',null),
('34','Sidi Embarek',null),
('34','Tefreg',null),
('34','Taglait',null),
('34','Teniet En Nasr',null),
('34','Tassameurt',null),
('34','Tixter',null),
('35','Boumerdes',null),
('35','Boudouaou',null),
('35','Afir',null),
('35','Bordj Menaiel',null),
('35','Baghlia',null),
('35','Sidi Daoud',null),
('35','Naciria',null),
('35','Djinet',null),
('35','Issers',null),
('35','Zemmouri',null),
('35','Si Mustapha',null),
('35','Tidjelabine',null),
('35','Chabet el Ameur',null),
('35','Thenia',null),
('35','Timezrit',null),
('35','Corso',null),
('35','Ouled Moussa',null),
('35','Larbatache',null),
('35','Bouzegza Keddara',null),
('35','Taourga',null),
('35','Ouled Aissa',null),
('35','Ben Choud',null),
('35','Dellys',null),
('35','Ammal',null),
('35','Beni Amrane',null),
('35','Souk El Had',null),
('35','Boudouaou El Bahri',null),
('35','Ouled Hedadj',null),
('35','Leghata',null),
('35','Hammedi',null),
('35','Khemis El Khechna',null),
('35','El Kharrouba',null),
('36','AÃ¯n El Assel',null),
('36','AÃ¯n Kerma',null),
('36','Asfour',null),
('36','Ben Mehidi',null),
('36','Berrihane',null),
('36','Besbes',null),
('36','Bougous',null),
('36','Bouhadjar',null),
('36','Bouteldja',null),
('36','Chebaita Mokhtar',null),
('36','Chefia',null),
('36','Chihani',null),
('36','DrÃ©an',null),
('36','Echatt',null),
('36','El Aioun',null),
('36','El Kala',null),
('36','El Tarf',null),
('36','Hammam Beni Salah',null),
('36','Lac des Oiseaux',null),
('36','Oued Zitoun',null),
('36','Raml Souk',null),
('36','Souarekh',null),
('36','Zerizer',null),
('36','Zitouna',null),
('37','Oum el Assel',null),
('37','Tindouf',null),
('38','Ammari',null),
('38','Beni Chaib',null),
('38','Beni Lahcene',null),
('38','Boucaid',null),
('38','Bordj Bou Naama',null),
('38','Bordj El Emir Abdelkader',null),
('38','Khemisti',null),
('38','Larbaa',null),
('38','Lardjem',null),
('38','Layoune',null),
('38','Lazharia',null),
('38','Maacem',null),
('38','Melaab',null),
('38','Ouled Bessem',null),
('38','Sidi Abed',null),
('38','Sidi Boutouchent',null),
('38','Sidi Lantri',null),
('38','Sidi Slimane',null),
('38','Tamalaht',null),
('38','Theniet El Had',null),
('38','Tissemsilt',null),
('38','Youssoufia',null),
('39','El Oued',null),
('39','Robbah',null),
('39','Oued El Alenda',null),
('39','Bayadha',null),
('39','Nakhla',null),
('39','Guemar',null),
('39','Kouinine',null),
('39','Reguiba',null),
('39','Hamraia',null),
('39','Taghzout',null),
('39','Debila',null),
('39','Hassani Abdelkrim',null),
('39','Hassi Khalifa',null),
('39','Taleb Larbi',null),
('39','Douar El Ma',null),
('39','Sidi Aoun',null),
('39','Trifaoui',null),
('39','Magrane',null),
('39','Beni Guecha',null),
('39','Ourmas',null),
('39','El Ogla',null),
('39','Mih Ouansa',null),
('40','AÃ¯n Touila',null),
('40','Babar',null),
('40','Baghai',null),
('40','Bouhmama',null),
('40','Chechar',null),
('40','Chelia',null),
('40','Djellal',null),
('40','El Hamma',null),
('40','El Mahmal',null),
('40','El Oueldja',null),
('40','Ensigha',null),
('40','Kais',null),
('40','Khenchela',null),
('40','Khirane',null),
('40','M''Sara',null),
('40','M''Toussa',null),
('40','Ouled Rechache',null),
('40','Remila',null),
('40','Tamza',null),
('40','Taouzient',null),
('40','Yabous',null),
('41','Souk Ahras',null),
('41','Sedrata',null),
('41','Hanancha',null),
('41','Mechroha',null),
('41','Ouled Driss',null),
('41','Tiffech',null),
('41','Zaarouria',null),
('41','Taoura',null),
('41','Drea',null),
('41','Heddada',null),
('41','Khedara',null),
('41','Merahna',null),
('41','Ouled Moumene',null),
('41','Bir Bou Haouch',null),
('41','M''daourouch',null),
('41','Oum El Adhaim',null),
('41','AÃ¯n Zana',null),
('41','AÃ¯n Soltane',null),
('41','Ouillen',null),
('41','Sidi Fredj',null),
('41','Safel El Ouiden',null),
('41','Ragouba',null),
('41','Khemissa',null),
('41','Oued Keberit',null),
('41','Terraguelt',null),
('41','Zouabi',null),
('42','Tipaza',null),
('42','Menaceur',null),
('42','Larhat',null),
('42','Douaouda',null),
('42','Bourkika',null),
('42','Khemisti',null),
('42','Aghbal',null),
('42','Hadjout',null),
('42','Sidi Amar',null),
('42','Gouraya',null),
('42','Nador',null),
('42','Chaiba',null),
('42','AÃ¯n Tagourait',null),
('42','Cherchell',null),
('42','Damous',null),
('42','Merad',null),
('42','Fouka',null),
('42','Bou IsmaÃ¯l',null),
('42','Ahmar El AÃ¯n',null),
('42','Bouharoun',null),
('42','Sidi Ghiles',null),
('42','Messelmoun',null),
('42','Sidi Rached',null),
('42','KolÃ©a',null),
('42','Attatba',null),
('42','Sidi Semiane',null),
('42','Beni Milleuk',null),
('42','Hadjeret Ennous',null),
('43','Ahmed Rachedi',null),
('43','AÃ¯n Beida Harriche',null),
('43','AÃ¯n Mellouk',null),
('43','AÃ¯n Tine',null),
('43','Amira ArrÃ¨s',null),
('43','Benyahia Abderrahmane',null),
('43','Bouhatem',null),
('43','Chelghoum Laid',null),
('43','Chigara',null),
('43','Derradji Bousselah',null),
('43','El Mechira',null),
('43','Elayadi Barbes',null),
('43','Ferdjioua',null),
('43','Grarem Gouga',null),
('43','Hamala',null),
('43','Mila',null),
('43','Minar Zarza',null),
('43','Oued Athmania',null),
('43','Oued Endja',null),
('43','Oued Seguen',null),
('43','Ouled Khalouf',null),
('43','Rouached',null),
('43','Sidi Khelifa',null),
('43','Sidi Merouane',null),
('43','Tadjenanet',null),
('43','Tassadane Haddada',null),
('43','Teleghma',null),
('43','Terrai Bainen',null),
('43','Tessala LemtaÃ¯',null),
('43','Tiberguent',null),
('43','Yahia Beni Guecha',null),
('43','Zeghaia',null),
('44','AÃ¯n Defla',null),
('44','AÃ¯n Bouyahia',null),
('44','AÃ¯n Benian',null),
('44','AÃ¯n Lechiekh',null),
('44','AÃ¯n Soltane',null),
('44','AÃ¯n Torki',null),
('44','Arib',null),
('44','Bathia',null),
('44','Belaas',null),
('44','Ben Allal',null),
('44','Birbouche',null),
('44','Bir Ould Khelifa',null),
('44','Bordj Emir Khaled',null),
('44','Boumedfaa',null),
('44','Bourached',null),
('44','Djelida',null),
('44','Djemaa Ouled Cheikh',null),
('44','Djendel',null),
('44','El Abadia',null),
('44','El Amra',null),
('44','El Attaf',null),
('44','El Hassania',null),
('44','El Maine',null),
('44','Hammam Righa',null),
('44','Hoceinia',null),
('44','Khemis Miliana',null),
('44','Mekhatria',null),
('44','Miliana',null),
('44','Oued Chorfa',null),
('44','Oued Djemaa',null),
('44','Rouina',null),
('44','Sidi Lakhdar',null),
('44','Tacheta Zougagha',null),
('44','Tarik Ibn Ziad',null),
('44','Tiberkanine',null),
('44','Zeddine',null),
('45','NaÃ¢ma',null),
('45','Mecheria',null),
('45','AÃ¯n Sefra',null),
('45','Tiout',null),
('45','Sfissifa',null),
('45','Moghrar',null),
('45','Assela',null),
('45','Djeniene Bourezg',null),
('45','AÃ¯n Ben Khelil',null),
('45','Makman Ben Amer',null),
('45','Kasdir',null),
('45','El Biod',null),
('46','Aghlal',null),
('46','AÃ¯n El Arbaa',null),
('46','AÃ¯n Kihal',null),
('46','AÃ¯n TÃ©mouchent',null),
('46','AÃ¯n Tolba',null),
('46','Aoubellil',null),
('46','Beni Saf',null),
('46','Bouzedjar',null),
('46','Chaabat El Leham',null),
('46','Chentouf',null),
('46','El Amria',null),
('46','El Emir Abdelkader',null),
('46','El Malah',null),
('46','El Messaid',null),
('46','Hammam Bouhadjar',null),
('46','Hassasna',null),
('46','Hassi El Ghella',null),
('46','Oued Berkeche',null),
('46','Oued Sabah',null),
('46','Ouled Boudjemaa',null),
('46','Ouled Kihal',null),
('46','OulhaÃ§a El Gheraba',null),
('46','Sidi Ben Adda',null),
('46','Sidi Boumedienne',null),
('46','Sidi Ouriache',null),
('46','Sidi Safi',null),
('46','Tamzoura',null),
('46','Terga',null),
('47','Berriane',null),
('47','Bounoura',null),
('47','Dhayet Bendhahoua',null),
('47','El Atteuf',null),
('47','El Guerrara',null),
('47','GhardaÃ¯a',null),
('47','Mansoura',null),
('47','Metlili',null),
('47','Sebseb',null),
('47','Zelfana',null),
('48','AÃ¯n Rahma',null),
('48','AÃ¯n Tarek',null),
('48','Ammi Moussa',null),
('48','Belassel Bouzegza',null),
('48','Bendaoud',null),
('48','Beni Dergoun',null),
('48','Beni Zentis',null),
('48','Dar Ben Abdellah',null),
('48','Djidioua',null),
('48','El Guettar',null),
('48','El Hamadna',null),
('48','El Hassi',null),
('48','El Matmar',null),
('48','El Ouldja',null),
('48','Had Echkalla',null),
('48','Hamri',null),
('48','Kalaa',null),
('48','Lahlef',null),
('48','Mazouna',null),
('48','Mediouna',null),
('48','Mendes',null),
('48','Merdja Sidi Abed',null),
('48','Ouarizane',null),
('48','Oued Essalem',null),
('48','Oued Rhiou',null),
('48','Ouled Aiche',null),
('48','Oued El Djemaa',null),
('48','Ouled Sidi Mihoub',null),
('48','Ramka',null),
('48','Relizane',null),
('48','Sidi Khettab',null),
('48','Sidi Lazreg',null),
('48','Sidi M''Hamed Ben Ali',null),
('48','Sidi M''Hamed Benaouda',null),
('48','Sidi Saada',null),
('48','Souk El Had',null),
('48','Yellel',null),
('48','Zemmora',null),
('49','Charouine',null),
('49','Ksar Kaddour',null),
('49','Timimoun',null),
('49','Ouled SaÃ¯d',null),
('49','Tinerkouk',null),
('49','Deldoul',null),
('49','Metarfa',null),
('49','Aougrout',null),
('49','Talmine',null),
('49','Ouled AÃ¯ssa',null),
('50','Bordj Badji Mokhtar',null),
('50','Timiaouine',null),
('51','Besbes',null),
('51','Doucen',null),
('51','Ech ChaÃ¯ba',null),
('51','Ouled Djellal',null),
('51','Ras El Miaad',null),
('51','Sidi Khaled',null),
('52','Ouled Khoudir',null)
on conflict (wilaya_code, name_fr) do update set
  name_ar = excluded.name_ar;

insert into public.communes (wilaya_code, name_fr, name_ar) values
('52','Timoudi',null),
('52','BÃ©ni AbbÃ¨s',null),
('52','Beni Ikhlef',null),
('52','Igli',null),
('52','Tabelbala',null),
('52','El Ouata',null),
('52','Kerzaz',null),
('52','Ksabi',null),
('52','Tamtert',null),
('53','In Ghar',null),
('53','In Salah',null),
('53','Foggaret Ezzaouia',null),
('54','In Guezzam',null),
('54','Tin Zaouatine',null),
('55','Benaceur',null),
('55','Blidet Amor',null),
('55','El Allia',null),
('55','El Borma',null),
('55','El Hadjira',null),
('55','Megarine',null),
('55','M''Naguer',null),
('55','Nezla',null),
('55','Sidi Slimane',null),
('55','Taibet',null),
('55','Tamacine',null),
('55','Tebesbest',null),
('55','Touggourt',null),
('55','Zaouia El Abidia',null),
('56','Djanet',null),
('56','Bordj El Haouas',null),
('57','Still',null),
('57','M''Rara',null),
('57','Sidi Khellil',null),
('57','Tendla',null),
('57','El M''Ghair',null),
('57','Djamaa',null),
('57','Oum Touyour',null),
('57','Sidi Amrane',null),
('58','El Menia',null),
('58','Hassi Fehal',null),
('58','Hassi Gara',null)
on conflict (wilaya_code, name_fr) do update set
  name_ar = excluded.name_ar;


